resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/19.yaml

packages:
- .
- ../sliceofpy

#extra-deps:
# - sliceofpy-1.0.0@sha256:56a8486c7fec63e4b21c3cfc6a2d88c2c516c94622fdca64375771f82ad34124,2360
